services:
  postgres:
    extends:
      file: ./backend/hasura/docker-compose.yml
      service: postgres
  graphql-engine:
    extends:
      file: ./backend/hasura/docker-compose.yml
      service: graphql-engine
  frontend:
    extends:
      file: ./frontend/docker-compose.yml
      service: frontend
volumes:
  db_data:
